"""Add has_pos and VirtualSession

Revision ID: 0f0dd46deb52
Revises: d4da9e08c95a
Create Date: 2026-04-20 21:12:39.254955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f0dd46deb52'
down_revision: Union[str, Sequence[str], None] = 'd4da9e08c95a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('has_pos', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'has_pos')
    # ### end Alembic commands ###
