"""add hardware config fields

Revision ID: 92611163620f
Revises: f6b4911cf7e4
Create Date: 2026-04-21 14:16:36.017666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92611163620f'
down_revision: Union[str, Sequence[str], None] = 'f6b4911cf7e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('printer_config', sa.String(), nullable=True))
    op.add_column('stores', sa.Column('auto_kitchen_print', sa.Boolean(), nullable=True))
    op.add_column('stores', sa.Column('allow_staff_order', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'allow_staff_order')
    op.drop_column('stores', 'auto_kitchen_print')
    op.drop_column('stores', 'printer_config')
    # ### end Alembic commands ###
