"""Add hardware config fields to Store

Revision ID: f6b4911cf7e4
Revises: 0f0dd46deb52
Create Date: 2026-04-20 23:45:01.704773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6b4911cf7e4'
down_revision: Union[str, Sequence[str], None] = '0f0dd46deb52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
